/* Generated by translate.py. Real native pointers; no ARM bus, scheduler or interpreter. */
#include <stdint.h>
#include <string.h>
typedef char require_32bit_native_pointer[sizeof(void*)==4?1:-1];
typedef struct {unsigned n,z,c,v;} Flags;
static void nz(Flags*f,uint32_t r){f->n=r>>31;f->z=r==0;}
static void af(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=((uint64_t)x+y)>>32;f->v=((~(x^y)&(x^r))>>31);}
static void sf(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=x>=y;f->v=((x^y)&(x^r))>>31;}
static uint32_t shift(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(32-n))&1):0;x=n<32?x<<n:0;}nz(f,x);return x;}
static uint32_t shift_right(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(n-1))&1):0;x=n<32?x>>n:0;}nz(f,x);return x;}
#define MEM(N,T) static uint32_t ld##N(uint32_t p){T v;memcpy(&v,(void*)(uintptr_t)p,sizeof(v));return v;} static void st##N(uint32_t p,uint32_t v){T w=v;memcpy((void*)(uintptr_t)p,&w,sizeof(w));}
MEM(8,uint8_t) MEM(16,uint16_t) MEM(32,uint32_t)
extern void *Heap_Alloc(int,uint32_t);
extern void MIi_CpuClear32(uint32_t,void*,uint32_t);

extern unsigned char ssdata_unk_02004A44__020F5730[];
uint32_t native_GBSounds_GetGBSeqNoByDSSeqNo(uint32_t a0,uint32_t a1,uint32_t a2,uint32_t a3) {
uint32_t r0=a0,r1=a1,r2=a2,r3=a3,r4=0,r5=0,r6=0,r7=0,lr=0;
uint32_t stack[2]; uint32_t sp=(uint32_t)(uintptr_t)(stack+2);
Flags f={0}; uint32_t x,y,res;
sp-=8;
st32(sp+0,r3);
st32(sp+4,r4);
r2=(uint32_t)(uintptr_t)ssdata_unk_02004A44__020F5730;
r4=0;
nz(&f,r4);
_02005C72:
r3=shift(&f,r4,2);
r1=ld16(r2 + r3);
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _02005C82;
r0=(uint32_t)(uintptr_t)ssdata_unk_02004A44__020F5730 + 2;
r0=ld16(r0 + r3);
r3=ld32(sp+0);
r4=ld32(sp+4);
sp+=8;
return r0;
_02005C82:
x=r4; y=1; res=x+y;
r1=res;
af(&f,x,y,res);
r1=shift(&f,r1,0x10);
r4=shift_right(&f,r1,0x10);
x=r4; y=0x88; res=x-y;
sf(&f,x,y,res);
if (!f.c) goto _02005C72;
r3=ld32(sp+0);
r4=ld32(sp+4);
sp+=8;
return r0;
}
