/* Generated by translate.py. Real native pointers; no ARM bus, scheduler or interpreter. */
#include <stdint.h>
#include <string.h>
typedef char require_32bit_native_pointer[sizeof(void*)==4?1:-1];
typedef struct {unsigned n,z,c,v;} Flags;
static void nz(Flags*f,uint32_t r){f->n=r>>31;f->z=r==0;}
static void af(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=((uint64_t)x+y)>>32;f->v=((~(x^y)&(x^r))>>31);}
static void sf(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=x>=y;f->v=((x^y)&(x^r))>>31;}
static uint32_t shift(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(32-n))&1):0;x=n<32?x<<n:0;}nz(f,x);return x;}
static uint32_t shift_right(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(n-1))&1):0;x=n<32?x>>n:0;}nz(f,x);return x;}
#define MEM(N,T) static uint32_t ld##N(uint32_t p){T v;memcpy(&v,(void*)(uintptr_t)p,sizeof(v));return v;} static void st##N(uint32_t p,uint32_t v){T w=v;memcpy((void*)(uintptr_t)p,&w,sizeof(w));}
MEM(8,uint8_t) MEM(16,uint16_t) MEM(32,uint32_t)
extern void *Heap_Alloc(int,uint32_t);
extern void MIi_CpuClear32(uint32_t,void*,uint32_t);

extern unsigned char ssdata_overlay_40_ov40_02244E5C[];
uint32_t native_ov40_0222DAC0(uint32_t a0,uint32_t a1,uint32_t a2,uint32_t a3) {
uint32_t r0=a0,r1=a1,r2=a2,r3=a3,r4=0,r5=0,r6=0,r7=0,lr=0;
uint32_t stack[10]; uint32_t sp=(uint32_t)(uintptr_t)(stack+10);
Flags f={0}; uint32_t x,y,res;
sp-=12;
st32(sp+0,r3);
st32(sp+4,r4);
st32(sp+8,r5);
x=sp; y=0x1c; res=x-y;
sp=res;
r4=(uint32_t)(uintptr_t)ssdata_overlay_40_ov40_02244E5C;
x=r0; y=0; res=x+y;
r5=res;
af(&f,x,y,res);
x=r4;
r0=ld32(x+0);
r1=ld32(x+4);
r4=x+8;
x=sp; y=0; res=x+y;
r3=res;
x=r3; y=0; res=x+y;
r2=res;
af(&f,x,y,res);
x=r3;
st32(x+0,r0);
st32(x+4,r1);
r3=x+8;
x=r4;
r0=ld32(x+0);
r1=ld32(x+4);
r4=x+8;
x=r3;
st32(x+0,r0);
st32(x+4,r1);
r3=x+8;
x=r4;
r0=ld32(x+0);
r1=ld32(x+4);
r4=x+8;
x=r3;
st32(x+0,r0);
st32(x+4,r1);
r3=x+8;
r0=ld32(r4);
x=r5; y=0x5c; res=x+y;
r5=res;
af(&f,x,y,res);
st32(r3,r0);
r0=ld8(r5);
r0=shift(&f,r0,2);
r0=ld32(r2 + r0);
x=sp; y=0x1c; res=x+y;
sp=res;
r3=ld32(sp+0);
r4=ld32(sp+4);
r5=ld32(sp+8);
sp+=12;
return r0;
}
