/* Generated by translate.py. Real native pointers; no ARM bus, scheduler or interpreter. */
#include <stdint.h>
#include <string.h>
typedef char require_32bit_native_pointer[sizeof(void*)==4?1:-1];
typedef struct {unsigned n,z,c,v;} Flags;
static void nz(Flags*f,uint32_t r){f->n=r>>31;f->z=r==0;}
static void af(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=((uint64_t)x+y)>>32;f->v=((~(x^y)&(x^r))>>31);}
static void sf(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=x>=y;f->v=((x^y)&(x^r))>>31;}
static uint32_t shift(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(32-n))&1):0;x=n<32?x<<n:0;}nz(f,x);return x;}
static uint32_t shift_right(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(n-1))&1):0;x=n<32?x>>n:0;}nz(f,x);return x;}
#define MEM(N,T) static uint32_t ld##N(uint32_t p){T v;memcpy(&v,(void*)(uintptr_t)p,sizeof(v));return v;} static void st##N(uint32_t p,uint32_t v){T w=v;memcpy((void*)(uintptr_t)p,&w,sizeof(w));}
MEM(8,uint8_t) MEM(16,uint16_t) MEM(32,uint32_t)
extern void *Heap_Alloc(int,uint32_t);
extern void MIi_CpuClear32(uint32_t,void*,uint32_t);

extern unsigned char ssdata_unk_02033AE0__021D412C[];
uint32_t native_sub_0203410C(uint32_t a0,uint32_t a1,uint32_t a2,uint32_t a3) {
uint32_t r0=a0,r1=a1,r2=a2,r3=a3,r4=0,r5=0,r6=0,r7=0,lr=0;
uint32_t stack[4]; uint32_t sp=(uint32_t)(uintptr_t)(stack+4);
Flags f={0}; uint32_t x,y,res;
sp-=16;
st32(sp+0,r4);
st32(sp+4,r5);
st32(sp+8,r6);
st32(sp+12,lr);
x=r0; y=0; res=x+y;
r5=res;
af(&f,x,y,res);
r0=(uint32_t)(uintptr_t)ssdata_unk_02033AE0__021D412C;
x=r1; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
r0=ld32(r0);
x=r2; y=0; res=x+y;
r6=res;
af(&f,x,y,res);
x=r0; y=0; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _02034128;
r0=0xf;
nz(&f,r0);
r1=0x18;
nz(&f,r1);
r0=(uint32_t)(uintptr_t)Heap_Alloc((int)r0,r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r1=(uint32_t)(uintptr_t)ssdata_unk_02033AE0__021D412C;
st32(r1,r0);
_02034128:
r0=(uint32_t)(uintptr_t)ssdata_unk_02033AE0__021D412C;
r3=0;
nz(&f,r3);
r1=ld32(r0);
x=r3; y=0; res=x+y;
r2=res;
af(&f,x,y,res);
st32(r1,r5);
r1=ld32(r0);
st32(r1 + 4,r4);
r1=ld32(r0);
st32(r1 + 8,r6);
_0203413A:
r1=ld32(r0);
x=r1; y=r3; res=x+y;
r1=res;
af(&f,x,y,res);
x=r3; y=1; res=x+y;
r3=res;
af(&f,x,y,res);
st8(r1 + 0xc,r2);
x=r3; y=8; res=x-y;
sf(&f,x,y,res);
if (f.n!=f.v) goto _0203413A;
r0=(uint32_t)(uintptr_t)ssdata_unk_02033AE0__021D412C;
r0=ld32(r0);
st8(r0 + 0x14,r2);
r4=ld32(sp+0);
r5=ld32(sp+4);
r6=ld32(sp+8);
sp+=16;
return r0;
}
