/* Generated by translate.py. Real native pointers; no ARM bus, scheduler or interpreter. */
#include <stdint.h>
#include <string.h>
typedef char require_32bit_native_pointer[sizeof(void*)==4?1:-1];
typedef struct {unsigned n,z,c,v;} Flags;
static void nz(Flags*f,uint32_t r){f->n=r>>31;f->z=r==0;}
static void af(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=((uint64_t)x+y)>>32;f->v=((~(x^y)&(x^r))>>31);}
static void sf(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=x>=y;f->v=((x^y)&(x^r))>>31;}
static uint32_t shift(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(32-n))&1):0;x=n<32?x<<n:0;}nz(f,x);return x;}
static uint32_t shift_right(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(n-1))&1):0;x=n<32?x>>n:0;}nz(f,x);return x;}
#define MEM(N,T) static uint32_t ld##N(uint32_t p){T v;memcpy(&v,(void*)(uintptr_t)p,sizeof(v));return v;} static void st##N(uint32_t p,uint32_t v){T w=v;memcpy((void*)(uintptr_t)p,&w,sizeof(w));}
MEM(8,uint8_t) MEM(16,uint16_t) MEM(32,uint32_t)
extern void *Heap_Alloc(int,uint32_t);
extern void MIi_CpuClear32(uint32_t,void*,uint32_t);

extern unsigned char ssdata_unk_02037C94__021D4150[];
extern unsigned char sub_02038E94[];
extern unsigned char sub_02038EB0[];
extern unsigned char sub_02038EB4[];
extern unsigned char sub_02038EB8[];
extern unsigned char sub_02038F9C[];
extern unsigned char sub_02039DC4[];
extern unsigned char sub_02039DE4[];
extern unsigned char sub_02039E7C[];
uint32_t native_sub_020390C4(uint32_t a0,uint32_t a1,uint32_t a2,uint32_t a3) {
uint32_t r0=a0,r1=a1,r2=a2,r3=a3,r4=0,r5=0,r6=0,r7=0,lr=0;
uint32_t stack[1]; uint32_t sp=(uint32_t)(uintptr_t)(stack+1);
Flags f={0}; uint32_t x,y,res;
r0=(uint32_t)(uintptr_t)ssdata_unk_02037C94__021D4150;
r1=(uint32_t)(uintptr_t)sub_02038F9C;
r0=ld32(r0);
r0=ld32(r0 + 0x24);
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _020390D4;
r0=0;
nz(&f,r0);
return r0;
_020390D4:
r1=(uint32_t)(uintptr_t)sub_02038EB8;
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _020390DE;
r0=1;
nz(&f,r0);
return r0;
_020390DE:
r1=(uint32_t)(uintptr_t)sub_02038E94;
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _020390E8;
r0=3;
nz(&f,r0);
return r0;
_020390E8:
r1=(uint32_t)(uintptr_t)sub_02038EB0;
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _020390F2;
r0=4;
nz(&f,r0);
return r0;
_020390F2:
r1=(uint32_t)(uintptr_t)sub_02038EB4;
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _020390FC;
r0=5;
nz(&f,r0);
return r0;
_020390FC:
r1=(uint32_t)(uintptr_t)sub_02039DE4;
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _02039106;
r0=0;
nz(&f,r0);
return r0;
_02039106:
r1=(uint32_t)(uintptr_t)sub_02039DC4;
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _02039110;
r0=1;
nz(&f,r0);
return r0;
_02039110:
r1=(uint32_t)(uintptr_t)sub_02039E7C;
x=r0; y=r1; res=x-y;
sf(&f,x,y,res);
if (!f.z) goto _0203911A;
r0=3;
nz(&f,r0);
return r0;
_0203911A:
r0=2;
nz(&f,r0);
return r0;
}
