"""Generate a DS I/O register dispatcher for translated assembly.

The decompiled C reaches the DS registers through the SDK's `reg_*` macros,
which the native (X86/simulator) SDK resolves to individual variables. Hand
assembly instead loads the literal DS address (0x0400000C and friends) and
does pointer arithmetic on it, so a translated load or store has to be routed
back to the right SDK register variable at run time.

This reads the ARM9 SDK headers for the real DS address of every register and
the matching `reg_*` accessor macro, and emits a switch per access width. An
address or width with no accessor aborts with a [FATAL] line: no silent read
of zero, no dropped write.
"""
from pathlib import Path
import re, sys

HERE = Path(__file__).resolve().parent
HW = HERE.parents[1] / 'native-graphics/libntr/include/twl/hw'
BASE = 0x04000000

offsets, accessors = {}, {}
for header in sorted((HW / 'ARM9').glob('ioreg_*.h')):
    text = header.read_text()
    for name, value in re.findall(r'#define\s+REG_(\w+)_OFFSET\s+(0x[0-9a-fA-F]+|\d+)', text):
        offsets[name] = int(value, 0)
    for macro, reg, width in re.findall(
            r'#define\s+(reg_\w+)\s+\(\*\(REGType(?:(\d+))v\s*\*\)\s*REG_(\w+)_ADDR\)', text):
        pass
    for m in re.finditer(r'#define\s+(reg_\w+)\s+\(\*\(REGType(\d+)v\s*\*\)REG_(\w+)_ADDR\)', text):
        macro, width, name = m.group(1), int(m.group(2)), m.group(3)
        accessors.setdefault((name, width), macro)

# The native (X86/simulator) SDK does not declare every DS/TWL register; only
# emit cases for accessors it actually provides, so this file compiles against
# the headers the game itself uses.
available = set()
for header in sorted((HW / 'X86').glob('ioreg_*.h')):
    available.update(re.findall(r'#define\s+(reg_\w+)\s', header.read_text()))

by_width = {8: {}, 16: {}, 32: {}}
for (name, width), macro in accessors.items():
    if name in offsets and width in by_width and macro in available:
        by_width[width].setdefault(BASE + offsets[name], macro)

def build(excluded):
  out = ['/* Generated by gen_ioreg.py from the ARM9 SDK register headers. */',
       '#include <nitro.h>', '#include <stdio.h>', '#include <stdlib.h>', '#include <stdint.h>',
       'static void ss_io_bad(const char *what, uint32_t address) {',
       '    printf("[FATAL] translated assembly %s of unmapped DS register %08lx\\n", what, (unsigned long)address);',
       '    fflush(stdout); abort();',
       '}']
  kept = {w: 0 for w in by_width}
  for width in (8, 16, 32):
    out.append(f'uint32_t ss_io_read{width}(uint32_t address) {{')
    out.append('    switch (address) {')
    for addr, macro in sorted(by_width[width].items()):
        if macro in excluded: continue
        kept[width] += 1
        out.append(f'    case 0x{addr:08x}: return (uint32_t){macro};')
    out.append('    }')
    out.append(f'    ss_io_bad("{width}-bit read", address); return 0;')
    out.append('}')
    out.append(f'void ss_io_write{width}(uint32_t address, uint32_t value) {{')
    out.append('    switch (address) {')
    for addr, macro in sorted(by_width[width].items()):
        if macro in excluded: continue
        out.append(f'    case 0x{addr:08x}: {macro} = (uint{width}_t)value; return;')
    out.append('    }')
    out.append(f'    ss_io_bad("{width}-bit write", address);')
    out.append('}')
  (HERE / 'ds_ioreg.c').write_text('\n'.join(out) + '\n')
  return kept

# Registers the simulator SDK compiles out (TWL-only blocks) are dropped by
# compiling and removing whatever the compiler reports as undeclared; those
# addresses then abort loudly instead of silently reading zero.
import json, subprocess
cmd = json.loads((HERE.parents[1] / 'soulsilver-native-core/compile-command.json').read_text())
excluded = set()
for attempt in range(12):
    kept = build(excluded)
    r = subprocess.run(cmd + ['-c', str(HERE / 'ds_ioreg.c'), '-o', '/dev/null'],
                       capture_output=True, text=True)
    if r.returncode == 0:
        break
    new = set(re.findall(r"error: '(reg_\w+)' undeclared", r.stderr))
    if not new:
        sys.stderr.write(r.stderr[-3000:])
        raise SystemExit('ds_ioreg.c does not compile')
    excluded |= new
else:
    raise SystemExit('could not settle the register table')
(HERE / 'ds_ioreg-excluded.json').write_text(json.dumps(sorted(excluded), indent=1) + '\n')
print('mapped DS registers:', kept, 'excluded (not in the native SDK):', len(excluded))
