/* Generated by translate.py. Real native pointers; no ARM bus, scheduler or interpreter. */
#include <stdint.h>
#include <string.h>
typedef char require_32bit_native_pointer[sizeof(void*)==4?1:-1];
typedef struct {unsigned n,z,c,v;} Flags;
static void nz(Flags*f,uint32_t r){f->n=r>>31;f->z=r==0;}
static void af(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=((uint64_t)x+y)>>32;f->v=((~(x^y)&(x^r))>>31);}
static void sf(Flags*f,uint32_t x,uint32_t y,uint32_t r){nz(f,r);f->c=x>=y;f->v=((x^y)&(x^r))>>31;}
static uint32_t shift(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(32-n))&1):0;x=n<32?x<<n:0;}nz(f,x);return x;}
static uint32_t shift_right(Flags*f,uint32_t x,unsigned n){n&=255;if(n){f->c=n<=32?((x>>(n-1))&1):0;x=n<32?x>>n:0;}nz(f,x);return x;}
#define MEM(N,T) static uint32_t ld##N(uint32_t p){T v;memcpy(&v,(void*)(uintptr_t)p,sizeof(v));return v;} static void st##N(uint32_t p,uint32_t v){T w=v;memcpy((void*)(uintptr_t)p,&w,sizeof(w));}
MEM(8,uint8_t) MEM(16,uint16_t) MEM(32,uint32_t)
extern void *Heap_Alloc(int,uint32_t);
extern void MIi_CpuClear32(uint32_t,void*,uint32_t);

typedef struct UnkStruct_021D2230 UnkStruct_021D2230;
typedef struct DWCstAccUserData DWCAccUserData;
extern void *sub_0202C08C(UnkStruct_021D2230*);
extern int DWC_CheckUserData(const DWCAccUserData*);
extern void DWC_CreateUserData(DWCAccUserData*,uint32_t);
extern void DWC_ClearDirtyFlag(DWCAccUserData*);
extern void Heap_FreeExplicit(int,void*);
extern void NNS_SndSetMonoFlag(int);
extern void TP_RequestAutoSamplingStartAsync(uint16_t,uint16_t,void*,uint16_t);
extern void TP_RequestAutoSamplingStopAsync(void);
extern void TP_WaitBusy(int);
extern uint32_t TP_CheckBusy(int);
extern void GF_AssertFail(void);
extern void NNS_G3dGlbLightVector(int,int16_t,int16_t,int16_t);
extern void NNS_G3dGlbLightColor(int,uint16_t);
extern void NNS_G3dGlbMaterialColorDiffAmb(uint16_t,uint16_t,int);
extern void NNS_G3dGlbMaterialColorSpecEmi(uint16_t,uint16_t,int);
extern void NNS_G3dGlbPolygonAttr(int,int,int,int,int,int);
extern void NNS_G3dMdlSetMdlDiffAll(void*,uint16_t);
extern void NNS_G3dMdlSetMdlAmbAll(void*,uint16_t);
extern void NNS_G3dMdlSetMdlSpecAll(void*,uint16_t);
extern void NNS_G3dMdlSetMdlEmiAll(void*,uint16_t);
extern void NNS_G3dMdlSetMdlLightEnableFlagAll(void*,int);
extern void NNS_G3dMdlSetMdlPolygonModeAll(void*,int);
extern void NNS_G3dMdlSetMdlCullModeAll(void*,int);
extern void NNS_G3dMdlSetMdlPolygonIDAll(void*,int);
extern void NNS_G3dMdlSetMdlAlphaAll(void*,int);
extern void NNS_G3dMdlSetMdlFogEnableFlagAll(void*,int);
extern void NNS_G3dMdlSetMdlDepthTestCondAll(void*,int);
extern void NNS_G3dMdlSetMdl1DotAll(void*,int);
extern void NNS_G3dMdlSetMdlFarClipAll(void*,int);
extern void NNS_G3dMdlSetMdlXLDepthUpdateAll(void*,int);
extern int sub_0201A79C(void);
extern int sub_02034044(int);
extern int sub_02034084(int);
extern void sub_02035E9C(void);
extern void sub_02035F4C(void);
extern int sub_02035FF0(void);
extern void sub_0203611C(void);
extern void sub_02036298(void);
extern void sub_0203667C(void);
extern void sub_02036BE4(void);
extern void sub_020372E4(void);
extern void sub_02037334(void);
extern int sub_020373B4(uint16_t);
extern int sub_0203769C(void);
extern void sub_02037ADC(void);
extern void sub_0203540C(uint32_t);
extern int ov00_021EC9D4(void);
extern int WM_GetLinkLevel(void);
extern void sub_0203A930(int);
extern int sub_02037700(void);
extern int sub_020393C8(void);
extern int sub_020395B0(void);
extern int sub_020397FC(void);
extern void Sound_Stop(void);
extern void Save_Cancel(void *);
extern void NNS_SndPlayerMoveVolume(void *,int,int);
extern void GF_SndWorkSetGbSoundsVolume(uint8_t);
extern uint8_t GF_GetPlayerNoBySeq(int);
extern int GF_GetSndHandleByPlayerNo(int);
extern void GF_SndHandleSetInitialVolume(int,int);
extern void * GF_GetSoundHandle(int);
extern void NNS_SndPlayerSetTrackAllocatableChannel(void *,uint16_t,uint32_t);
extern int NNS_SndPlayerCountPlayingSeqByPlayerNo(int);
extern void * GF_SdatGetAttrPtr(uint32_t);
extern void * GetSoundDataPointer(void);
extern void GF_SndSetAllocatableChannelForBGMPlayer(uint32_t);
extern void sub_02005910(int);
extern int sub_02005908(void);
extern int NNS_SndCaptureIsActive(void);
extern void Sound_Stop(void);
extern void GF_Snd_LoadState(int);
extern int GF_Snd_SaveState(int *);
extern int PlayBGM(uint16_t);
extern int GF_Snd_LoadGroup(int);
extern int GF_Snd_LoadSeqEx(int,uint32_t);
extern int GF_Snd_LoadBank(int);
extern int GF_Snd_LoadWaveArc(int);
extern void sub_0200508C(uint16_t,int);
extern void sub_02005228(uint16_t,int);
extern void sub_02005260(uint16_t,int);
extern void sub_02005280(uint16_t,int);
extern void sub_020052A4(uint16_t,int);
extern void sub_020052C8(int);
typedef struct PlayerAvatar PlayerAvatar;
extern uint32_t PlayerAvatar_GetNextFacingDirection(PlayerAvatar*);
extern int32_t PlayerAvatar_GetUnk28(PlayerAvatar*);
extern int32_t PlayerAvatar_GetUnk2C(PlayerAvatar*);
typedef struct PlayerAvatar PlayerAvatar;
typedef struct LocalMapObject LocalMapObject;
typedef struct FieldSystem FieldSystem;
extern LocalMapObject * PlayerAvatar_GetMapObject(PlayerAvatar *);
extern FieldSystem * MapObject_GetFieldSystem(LocalMapObject *);
extern int MapObject_AreBitsSetForMovementScriptInit(LocalMapObject *);
extern uint32_t MapObject_GetMovementCommand(LocalMapObject *);
extern uint32_t MapObject_GetNextFacingDirection(LocalMapObject *);
extern void MapObject_SetFlagsBits(LocalMapObject *,int);
extern void MapObject_ClearFlagsBits(LocalMapObject *,int);
extern void MapObject_SetHeldMovement(LocalMapObject *,uint32_t);
extern void PlayerAvatar_SetUnk28Unk2C(PlayerAvatar *,int32_t,int32_t);
extern void PlayerAvatar_SetUnk8(PlayerAvatar *,uint32_t);
extern uint32_t PlayerAvatar_GetMoveState(PlayerAvatar *);
extern int32_t PlayerAvatar_GetState(PlayerAvatar *);
extern int32_t PlayerAvatar_GetUnk24(PlayerAvatar *);
extern void PlayerAvatar_SetUnk24(PlayerAvatar *,int32_t);
extern void PlayerAvatar_SetMoveState(PlayerAvatar *,uint32_t);
extern int sub_0205DE64(uint32_t);
extern int sub_0205D01C(PlayerAvatar *,int);
extern int sub_0205D240(PlayerAvatar *,int);
extern void sub_0205D2D0(PlayerAvatar *,int);
extern uint32_t sub_020611F4(uint32_t);
extern uint32_t sub_0206234C(int,uint32_t);
extern int sub_0206D494(FieldSystem *);
extern void PlayerAvatar_ClearFlag6(PlayerAvatar *);
extern void PlayerAvatar_ClearUnk24ClearFlag2(PlayerAvatar *);
extern int PlayerAvatar_CheckFlag6(PlayerAvatar *);
extern int PlayerAvatar_CheckForcedMovement(PlayerAvatar *);
extern int PlayerAvatar_CheckFlag7(PlayerAvatar *);
extern void PlayerAvatar_SetFlag1(PlayerAvatar *,int);
extern void PlayerAvatar_SetFlag2(PlayerAvatar *,int);
extern void PlayerAvatar_SetFlag5(PlayerAvatar *,int);
extern void PlayerAvatar_SetFlag7(PlayerAvatar *,int);
extern void PlayerAvatar_SetForcedMovement(PlayerAvatar *,int);
extern uint32_t sub_0205DAA8(PlayerAvatar *,LocalMapObject *,int);
extern uint32_t sub_0205DBF4(PlayerAvatar *,LocalMapObject *,int);
extern uint32_t sub_0205DB68(PlayerAvatar *,LocalMapObject *,int);
extern uint32_t sub_0205DCA0(PlayerAvatar *,LocalMapObject *,int);
extern uint32_t sub_0205DCFC(PlayerAvatar *,LocalMapObject *,int);
uint32_t native_ModelAttributes_Init(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ModelAttributes_Free(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ModelAttributes_ApplyGlobal(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ov01_021EA9B0(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ov01_021EAAE0(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ov01_021EAAF4(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ov01_021EAB08(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ov01_021EAB1C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ov01_021EAB30(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ModelAttributes_SetPolygonMode(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ModelAttributes_SetCullMode(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ModelAttributes_SetAlpha(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_ModelAttributes_SetMiscAttrEnabled(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0203A01C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_020399B8(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0203817C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02039998(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0203993C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02039A00(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02039918(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_020399A4(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_TouchpadInit(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_TouchpadStartAutoSampling(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_TouchpadStopAutoSampling(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_TouchpadPauseOnLidClose(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_TouchpadResumeOnLidOpen(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_020059D8(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02005D00(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_SndSetMonoFlag(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02005BFC(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02005990(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_SndHandleMoveVolume(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_GetCurrentPlayingBGM(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_SetVolumeBySeqNo(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_SoundSys_GetGBSoundsState(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GBSounds_GetGBSeqNoByDSSeqNo(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GBSounds_SetAllocatableChannels(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_SndPlayerCountPlayingSeqByPlayerNo(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_Sound_SetSceneAndPlayBGM(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_Sound_SetScene(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02005AF8(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_020058F4(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_020052E4(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02005060(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02004B24(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02005328(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GF_SetCurrentPlayingBGM(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_IsPaletteFadeFinished(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GetDeltaXByFacingDirection(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_GetDeltaYByFacingDirection(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02026DE0(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02026E18(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02036144(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_020355C8(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02035650(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205DD9C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205DDB8(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205DDD4(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205CBEC(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205CC4C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205CC74(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205D004(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205D07C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205D09C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205D0A8(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205D190(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205D1FC(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205D2A0(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205DA1C(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_0205DA34(uint32_t,uint32_t,uint32_t,uint32_t);
uint32_t native_sub_02004B24(uint32_t a0,uint32_t a1,uint32_t a2,uint32_t a3) {
uint32_t r0=a0,r1=a1,r2=a2,r3=a3,r4=0,r5=0,r6=0,r7=0,lr=0;
uint32_t stack[2]; uint32_t sp=(uint32_t)(uintptr_t)(stack+2);
Flags f={0}; uint32_t x,y,res;
sp-=8;
st32(sp+0,r4);
st32(sp+4,lr);
x=r0; y=0x4b; res=x-y;
sf(&f,x,y,res);
if (!f.c||f.z) goto _02004B2C;
if (1) goto _02004E42;
_02004B2C:
x=r0; res=x+x; af(&f,x,x,res); switch(x) {
case 0: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 1: r0=(uint32_t)(int32_t)(int16_t)150; nz(&f,r0); f.c=0; goto _02004BD0;
case 2: r0=(uint32_t)(int32_t)(int16_t)316; nz(&f,r0); f.c=0; goto _02004C76;
case 3: r0=(uint32_t)(int32_t)(int16_t)346; nz(&f,r0); f.c=0; goto _02004C94;
case 4: r0=(uint32_t)(int32_t)(int16_t)356; nz(&f,r0); f.c=0; goto _02004C9E;
case 5: r0=(uint32_t)(int32_t)(int16_t)366; nz(&f,r0); f.c=0; goto _02004CA8;
case 6: r0=(uint32_t)(int32_t)(int16_t)386; nz(&f,r0); f.c=0; goto _02004CBC;
case 7: r0=(uint32_t)(int32_t)(int16_t)504; nz(&f,r0); f.c=0; goto _02004D32;
case 8: r0=(uint32_t)(int32_t)(int16_t)396; nz(&f,r0); f.c=0; goto _02004CC6;
case 9: r0=(uint32_t)(int32_t)(int16_t)150; nz(&f,r0); f.c=0; goto _02004BD0;
case 10: r0=(uint32_t)(int32_t)(int16_t)150; nz(&f,r0); f.c=0; goto _02004BD0;
case 11: r0=(uint32_t)(int32_t)(int16_t)376; nz(&f,r0); f.c=0; goto _02004CB2;
case 12: r0=(uint32_t)(int32_t)(int16_t)406; nz(&f,r0); f.c=0; goto _02004CD0;
case 13: r0=(uint32_t)(int32_t)(int16_t)316; nz(&f,r0); f.c=0; goto _02004C76;
case 14: r0=(uint32_t)(int32_t)(int16_t)306; nz(&f,r0); f.c=0; goto _02004C6C;
case 15: r0=(uint32_t)(int32_t)(int16_t)432; nz(&f,r0); f.c=0; goto _02004CEA;
case 16: r0=(uint32_t)(int32_t)(int16_t)416; nz(&f,r0); f.c=0; goto _02004CDA;
case 17: r0=(uint32_t)(int32_t)(int16_t)150; nz(&f,r0); f.c=0; goto _02004BD0;
case 18: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 19: r0=(uint32_t)(int32_t)(int16_t)160; nz(&f,r0); f.c=0; goto _02004BDA;
case 20: r0=(uint32_t)(int32_t)(int16_t)150; nz(&f,r0); f.c=0; goto _02004BD0;
case 21: r0=(uint32_t)(int32_t)(int16_t)326; nz(&f,r0); f.c=0; goto _02004C80;
case 22: r0=(uint32_t)(int32_t)(int16_t)356; nz(&f,r0); f.c=0; goto _02004C9E;
case 23: r0=(uint32_t)(int32_t)(int16_t)150; nz(&f,r0); f.c=0; goto _02004BD0;
case 24: r0=(uint32_t)(int32_t)(int16_t)442; nz(&f,r0); f.c=0; goto _02004CF4;
case 25: r0=(uint32_t)(int32_t)(int16_t)458; nz(&f,r0); f.c=0; goto _02004D04;
case 26: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 27: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 28: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 29: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 30: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 31: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 32: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 33: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 34: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 35: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 36: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 37: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 38: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 39: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 40: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 41: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 42: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 43: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 44: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 45: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 46: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 47: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 48: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 49: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 50: r0=(uint32_t)(int32_t)(int16_t)776; nz(&f,r0); f.c=0; goto _02004E42;
case 51: r0=(uint32_t)(int32_t)(int16_t)474; nz(&f,r0); f.c=0; goto _02004D14;
case 52: r0=(uint32_t)(int32_t)(int16_t)494; nz(&f,r0); f.c=0; goto _02004D28;
case 53: r0=(uint32_t)(int32_t)(int16_t)504; nz(&f,r0); f.c=0; goto _02004D32;
case 54: r0=(uint32_t)(int32_t)(int16_t)514; nz(&f,r0); f.c=0; goto _02004D3C;
case 55: r0=(uint32_t)(int32_t)(int16_t)524; nz(&f,r0); f.c=0; goto _02004D46;
case 56: r0=(uint32_t)(int32_t)(int16_t)540; nz(&f,r0); f.c=0; goto _02004D56;
case 57: r0=(uint32_t)(int32_t)(int16_t)550; nz(&f,r0); f.c=0; goto _02004D60;
case 58: r0=(uint32_t)(int32_t)(int16_t)560; nz(&f,r0); f.c=0; goto _02004D6A;
case 59: r0=(uint32_t)(int32_t)(int16_t)570; nz(&f,r0); f.c=0; goto _02004D74;
case 60: r0=(uint32_t)(int32_t)(int16_t)580; nz(&f,r0); f.c=0; goto _02004D7E;
case 61: r0=(uint32_t)(int32_t)(int16_t)590; nz(&f,r0); f.c=0; goto _02004D88;
case 62: r0=(uint32_t)(int32_t)(int16_t)600; nz(&f,r0); f.c=0; goto _02004D92;
case 63: r0=(uint32_t)(int32_t)(int16_t)610; nz(&f,r0); f.c=0; goto _02004D9C;
case 64: r0=(uint32_t)(int32_t)(int16_t)484; nz(&f,r0); f.c=0; goto _02004D1E;
case 65: r0=(uint32_t)(int32_t)(int16_t)524; nz(&f,r0); f.c=0; goto _02004D46;
case 66: r0=(uint32_t)(int32_t)(int16_t)620; nz(&f,r0); f.c=0; goto _02004DA6;
case 67: r0=(uint32_t)(int32_t)(int16_t)494; nz(&f,r0); f.c=0; goto _02004D28;
case 68: r0=(uint32_t)(int32_t)(int16_t)652; nz(&f,r0); f.c=0; goto _02004DC6;
case 69: r0=(uint32_t)(int32_t)(int16_t)636; nz(&f,r0); f.c=0; goto _02004DB6;
case 70: r0=(uint32_t)(int32_t)(int16_t)672; nz(&f,r0); f.c=0; goto _02004DDA;
case 71: r0=(uint32_t)(int32_t)(int16_t)688; nz(&f,r0); f.c=0; goto _02004DEA;
case 72: r0=(uint32_t)(int32_t)(int16_t)704; nz(&f,r0); f.c=0; goto _02004DFA;
case 73: r0=(uint32_t)(int32_t)(int16_t)724; nz(&f,r0); f.c=0; goto _02004E0E;
case 74: r0=(uint32_t)(int32_t)(int16_t)744; nz(&f,r0); f.c=0; goto _02004E22;
case 75: r0=(uint32_t)(int32_t)(int16_t)760; nz(&f,r0); f.c=0; goto _02004E32;
default: __builtin_trap(); }
_02004BD0:
r0=1;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004BDA:
r0=1;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
r0=1423;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1425;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1427;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1422;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1428;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1430;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1615;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1410;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1826;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1411;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1412;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1413;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1415;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1597;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1602;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1418;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=1409;
r1=1;
nz(&f,r1);
r0=GF_Snd_LoadSeqEx((int)r0,(uint32_t)r1);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
if (1) goto _02004E48;
_02004C6C:
r0=14;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004C76:
r0=2;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004C80:
r0=768>>8;
nz(&f,r0);
r0=shift(&f,r0,8);
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=3;
nz(&f,r0);
r0=shift(&f,r0,8);
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004C94:
r0=13;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004C9E:
r0=1;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CA8:
r0=2;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CB2:
r0=1;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CBC:
r0=11;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CC6:
r0=1;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CD0:
r0=14;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CDA:
r0=1;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=8;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CEA:
r0=1;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004CF4:
r0=770;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=770;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D04:
r0=771;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=771;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D14:
r0=3;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D1E:
r0=6;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D28:
r0=5;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D32:
r0=9;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D3C:
r0=10;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D46:
r0=757;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=757;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D56:
r0=12;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D60:
r0=7;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D6A:
r0=8;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D74:
r0=15;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D7E:
r0=3;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D88:
r0=5;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D92:
r0=15;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004D9C:
r0=4;
nz(&f,r0);
r0=GF_Snd_LoadGroup((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004DA6:
r0=767;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=767;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004DB6:
r0=769;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=769;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004DC6:
r0=764>>2;
nz(&f,r0);
r0=shift(&f,r0,2);
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=764>>2;
nz(&f,r0);
r0=shift(&f,r0,2);
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004DDA:
r0=773;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=773;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004DEA:
r0=774;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=774;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004DFA:
r0=772>>2;
nz(&f,r0);
r0=shift(&f,r0,2);
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=772>>2;
nz(&f,r0);
r0=shift(&f,r0,2);
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004E0E:
r0=776>>2;
nz(&f,r0);
r0=shift(&f,r0,2);
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=776>>2;
nz(&f,r0);
r0=shift(&f,r0,2);
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004E22:
r0=775;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=775;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004E32:
r0=777;
r0=GF_Snd_LoadBank((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r0=777;
r0=GF_Snd_LoadWaveArc((int)r0);
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
x=r0; y=0; res=x+y;
r4=res;
af(&f,x,y,res);
if (1) goto _02004E48;
_02004E42:
GF_AssertFail();
r1=0xa1a1a1a1; r2=0xa2a2a2a2; r3=0xa3a3a3a3; f=(Flags){0}; /* caller-clobbered */
r4=0;
nz(&f,r4);
_02004E48:
x=r4; y=0; res=x+y;
r0=res;
af(&f,x,y,res);
r4=ld32(sp+0);
sp+=8;
return r0;
}
#include "../library.h"
void sub_02004B24(int a0){native_sub_02004B24((uint32_t)a0,0,0,0);}
